### ISSUE TITLE
Resources don’t save

### ISSUE THREAD

**Issue by Rushil13579** [HighestDreams/Graves#1]
Was just testing out the plugin, and the resources don't get saved. [Settings.yml & Grave.png]

**Comment by Rushil13579** [comment]
It creates a settings.yml but its empty

**Comment by Endermanbugzjfc** [comment]
Can you name issues properly please...?

**Comment by HighestDreams** [comment]
> It creates a settings.yml but its empty

Bug fixed, thanks for reporting ;)
